apiVersion: v1
kind: Pod
metadata:
  name: es
  labels:
    app: es
spec:
  containers:
  - name: es
    image: elasticsearch:5
    ports:
    - containerPort: 9200
    - containerPort: 9300
    env:
    - name: ES_JAVA_OPTS
      value: "-Xms1g -Xmx1g"
---
apiVersion: v1
kind: Service
metadata:
  name: es
spec:
#  type: NodePort
  selector:
    app: es
  ports:
  - name: http
    port: 9200
    protocol: TCP
#    nodePort: 39200
  - name: transport
    port: 9300
    protocol: TCP
#    nodePort: 39300
