apiVersion: v1
kind: Pod
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  containers:
  - name: kibana
    image: kibana:5
    ports:
    - containerPort: 5601
    env:
    - name: ELASTICSEARCH_URL
      value: http://es:9200
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
#  type: NodePort
  selector:
    app: kibana
  ports:
  - port: 5601
#    nodePort: 35601
