apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: monitoring2
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    args:
    - bash
    - -c
    - "apt-get update -y && apt-get install -y curl nmap netcat socat dnsutils && sleep 36000"
