# Add Rule to etcd security group

#  - name: etcd access for k8s
#    local_action:
#     module: cs_securitygroup_rule
#     name: "{{ etcd_security_group_name }}"
#     start_port: 4001
#     end_port: 4001
#     user_security_group: "{{ k8s_security_group_name }}"

# Rules for the k8s security group

# internal
  - name: flannel etcd 2379
    local_action:
     module: cs_securitygroup_rule
     security_group: "{{ k8s_security_group_name }}"
     start_port: 2379
     end_port: 2379
     user_security_group: "{{ k8s_security_group_name }}"

  - name: flannel etcd 2380
    local_action:
     module: cs_securitygroup_rule
     security_group: "{{ k8s_security_group_name }}"
     start_port: 2380
     end_port: 2380
     user_security_group: "{{ k8s_security_group_name }}"

  - name: k8s 8080
    local_action:
     module: cs_securitygroup_rule
     security_group: "{{ k8s_security_group_name }}"
     start_port: 8080
     end_port: 8080
     user_security_group: "{{ k8s_security_group_name }}"

  - name: flannel UDP 8472
    local_action:
     module: cs_securitygroup_rule
     security_group: "{{ k8s_security_group_name }}"
     start_port: 8472
     end_port: 8472
     protocol: udp
     user_security_group: "{{ k8s_security_group_name }}"

  - name: kubelet logs and exec TCP 10250
    local_action:
     module: cs_securitygroup_rule
     security_group: "{{ k8s_security_group_name }}"
     start_port: 10250
     end_port: 10250
     protocol: tcp
     user_security_group: "{{ k8s_security_group_name }}"

# external access

  - name: SSH for k8s
    local_action:
     module: cs_securitygroup_rule
     security_group: "{{ k8s_security_group_name }}"
     start_port: 22
     end_port: 22

  - name: k8s public secure
    local_action:
     module: cs_securitygroup_rule
     security_group: "{{ k8s_security_group_name }}"
     start_port: 443
     end_port: 443
